# Generated by Django 3.1.4 on 2021-01-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_image_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
    ]
