# Generated by Django 3.1.4 on 2021-01-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
