# Generated by Django 3.1.4 on 2021-01-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_auto_20210105_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
