# Generated by Django 3.1.4 on 2021-01-06 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0013_image_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='post_unlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
