# Generated by Django 3.1.4 on 2021-01-06 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0014_image_unlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='post_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
