# Generated by Django 3.1.4 on 2021-01-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0015_image_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='follow',
        ),
    ]
